apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hsr.name" . }}-next
  labels:
    app.kubernetes.io/name: {{ include "hsr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  DATABASE_URL: {{ include "hsr.dbConnectionString" (dict "dbCredential" .Values.secrets.dbCredential) | b64enc | quote }}