apiVersion: v1
name: hsr
version: v0.1.0
description: Honkai Starrail official website Helm chart
type: application
home: The URL of this projects home page (optional)
sources:
  - https://github.com/Peerapon966/hsr
dependencies:
  - name: ingress-nginx
    version: 4.12.2
    repository: https://kubernetes.github.io/ingress-nginx
maintainers:
  - name: Peerapon966
    url: https://github.com/Peerapon966
appVersion: "v0.0.1"
