{{- if .Values.phpmyadmin.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hsr.name" . }}-phpmyadmin
  labels:
    app.kubernetes.io/name: {{ include "hsr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  PMA_HOSTS: {{ (include "hsr.dbHost" .) | b64enc | quote }}
  PMA_USER: {{ .Values.mysql.connection.user | b64enc | quote }}
  PMA_PASSWORD: {{ .Values.mysql.connection.password | b64enc | quote }}
  PMA_PORT: {{ toString .Values.mysql.connection.port | b64enc | quote }}
  PMA_ARBITRARY: {{ default true .Values.phpmyadmin.arbitrary | ternary "1" "0" | b64enc | quote }}
{{- end }}