{{- if .Values.redis.useLocal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hsr.name" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "hsr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  REDIS_PASSWORD: {{ .Values.redis.connection.password | b64enc | quote }}
{{- end }}