{{- if .Values.redis.useLocal }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hsr.name" . }}-redis
spec:
  clusterIP: None
  selector:
    app: {{ include "hsr.name" . }}-redis
  ports:
    - protocol: TCP
      port: {{ int (default 6379 .Values.redis.connection.port) }}
      targetPort: 6379
{{- end }}