apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cngp-cluster.labels" . | nindent 4 }}
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: {{ .Values.version }}
  instances: {{ .Values.replicas }}
  {{- if .Values.extensions }}
  postgresql:
    extensions:
    {{- range .Values.extensions }}
      - name: {{ . }}
    {{- end }}
  {{- end }}
  bootstrap:
    initdb:
      database: {{ .Values.database.name }}
      owner: {{ .Values.database.username }}
      secret:
        name: {{ .Values.postgres.name }}-user
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: {{ .Values.postgres.name }}-initdb
            key: schema.sql
  storage:
    storageClass: {{ .Values.storage.className }}
    size: {{ .Values.storage.size }}
  {{- if .Values.walStorage.enabled }}
  walStorage:
    storageClass: {{ .Values.walStorage.className }}
    size: {{ .Values.walStorage.size }}
  {{- end }}
