{{- if .Values.initdb.initSql }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-initsql
  namespace: {{ .Release.Namespace }}
data:
  init.sql: {{ .Values.initdb.initSql }}
---
{{- end }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cngp-cluster.labels" . | nindent 4 }}
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: {{ .Values.version }}
  instances: {{ .Values.replicas }}
  {{- if .Values.extensions }}
  postgresql:
    extensions:
    {{- range .Values.extensions }}
      - name: {{ . }}
    {{- end }}
  {{- end }}
  superuserSecret:
    name: {{ .Release.Name }}-postgres-role
  {{- if .Values.roles }}
  managed:
    roles:
    {{- range $key, $value := .Values.roles }}
      - name: {{ $value.username }}
        ensure: present
        login: {{ $value.login }}
        superuser: {{ $value.superuser }}
        passwordSecret:
          name: {{ $.Release.Name }}-{{ $key }}-role
        {{- if $value.inRoles }}
        inRoles:
        {{- range $value.inRoles }}
          - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}
  {{- end }}
  bootstrap:
    initdb:
      database: {{ .Values.initdb.database }}
      owner: {{ .Values.initdb.owner.username }}
      secret:
        name: {{ .Release.Name }}-db-owner-role
      {{- if .Values.initdb.initSql }}
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: {{ .Release.Name }}-initsql
            key: init.sql
      {{- end }}
  storage:
    storageClass: {{ .Values.storage.className }}
    size: {{ .Values.storage.size }}
  {{- if .Values.walStorage.enabled }}
  walStorage:
    storageClass: {{ .Values.walStorage.className }}
    size: {{ .Values.walStorage.size }}
  {{- end }}
