{{- if .Values.vault.connection.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vault-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cngp-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.vault.connection.caBundle }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cngp-cluster.labels" . | nindent 4 }}
spec:
  address: {{ .Values.vault.connection.server }}
  caCertSecretRef: {{ .Release.Name }}-vault-ca
---
{{- end }}
{{- if .Values.vault.auth.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.auth.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cngp-cluster.labels" . | nindent 4 }}
---
{{- end }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cngp-cluster.labels" . | nindent 4 }}
spec:
  vaultConnectionRef: {{ ternary .Release.Name .Values.vault.connectionRef .Values.vault.connection.create }}
  method: kubernetes
  mount: {{ .Values.vault.kubernetesAuthMountPath }}
  kubernetes:
    role: {{ .Values.vault.auth.role }}
    serviceAccount: {{ .Values.vault.auth.serviceAccount.name }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $.Release.Name }}-postgres-role
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cngp-cluster.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ $.Release.Name }}
  mount: {{ $.Values.vault.kvEngine.mountPath }}
  type: kv-{{ $.Values.vault.kvEngine.version }}
  path: {{ .Values.postgres.vaultSecretPath }}
  refreshAfter: 10m
  destination:
    name: {{ $.Release.Name }}-postgres-role
    labels:
      cnpg.io/reload: "true"
    create: true
    overwrite: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $.Release.Name }}-db-owner-role
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cngp-cluster.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ $.Release.Name }}
  mount: {{ $.Values.vault.kvEngine.mountPath }}
  type: kv-{{ $.Values.vault.kvEngine.version }}
  path: {{ .Values.initdb.owner.vaultSecretPath }}
  refreshAfter: 10m
  destination:
    name: {{ $.Release.Name }}-db-owner-role
    labels:
      cnpg.io/reload: "true"
    create: true
    overwrite: true
---
{{- range $key, $value := .Values.roles }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $.Release.Name }}-{{ $key }}-role
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cngp-cluster.labels" $ | nindent 4 }}
spec:
  vaultAuthRef: {{ $.Release.Name }}
  mount: {{ $.Values.vault.kvEngine.mountPath }}
  type: kv-{{ $.Values.vault.kvEngine.version }}
  path: {{ $value.vaultSecretPath }}
  refreshAfter: 10m
  destination:
    name: {{ $.Release.Name }}-{{ $key }}-role
    labels:
      cnpg.io/reload: "true"
    create: true
    overwrite: true
---
{{- end }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Release.Name }}-url
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cngp-cluster.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Release.Name }}
  mount: {{ .Values.vault.kvEngine.mountPath }}
  type: kv-{{ .Values.vault.kvEngine.version }}
  path: {{ .Values.initdb.owner.vaultSecretPath }}
  refreshAfter: 10m
  destination:
    name: {{ .Release.Name }}-url
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        rw:
          text: |
            {{ `{{- printf "postgresql://%s:%s@` }}{{ .Release.Name }}-rw.{{ .Release.Namespace }}.svc:5432/{{ .Values.initdb.database }}{{ `" (get .Secrets "username") (get .Secrets "password") -}}` }}
        {{- if gt (int .Values.replicas) 1 }}
        ro:
          text: |
            {{ `{{- printf "postgresql://%s:%s@` }}{{ .Release.Name }}-ro.{{ .Release.Namespace }}.svc:5432/{{ .Values.initdb.database }}{{ `" (get .Secrets "username") (get .Secrets "password") -}}` }}
        {{- end }}