apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hsr.name" . }}-phpmyadmin
  labels:
    app.kubernetes.io/name: {{ include "hsr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  PMA_HOSTS: {{ .Values.secrets.dbCredential.host | b64enc | quote }}
  PMA_USER: {{ .Values.secrets.dbCredential.user | b64enc | quote }}
  PMA_PASSWORD: {{ .Values.secrets.dbCredential.password | b64enc | quote }}
  PMA_PORT: {{ toString .Values.secrets.dbCredential.port | b64enc | quote }}
  PMA_ARBITRARY: {{ default true .Values.secrets.dbCredential.arbitrary | ternary "1" "0" | b64enc | quote }}