apiVersion: v1
kind: Service
metadata:
  name: {{ include "hsr.name" . }}-myphpadmin
spec:
  selector:
    app: {{ include "hsr.name" . }}-myphpadmin
  ports:
    - protocol: TCP
      port: {{ int (default 8080 .Values.secrets.dbCredential.port) }}
      targetPort: 80
