apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: next
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  # ingressClassName: traefik
  rules:
    - host: {{- .Values.hostname -}}
      http:
        paths:
          - path: {{ default "/" (.Values.next.path | quote) }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "hsr.name" . }}-next
                port:
                  number: {{ int (default 3000 .Values.next.port) }}
          {{- if .Values.phpmyadmin.enabled }}
          - path: {{ default "/phpmyadmin" (.Values.phpmyadmin.path | quote) }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "hsr.name" . }}-phpmyadmin
                port:
                  number: {{ int (default 8080 .Values.phpmyadmin.port) }}
          {{- end }}
          {{- if .Values.mailhog.enabled }}
          - path: {{ default "/mailhog" (.Values.mailhog.path | quote) }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "hsr.name" . }}-mailhog
                port:
                  number: {{ int (default 8025 .Values.mailhog.port) }}
          {{- end }}