{{- if .Values.mysql.useLocal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hsr.name" . }}-mysql
  labels:
    app.kubernetes.io/name: {{ include "hsr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  NEXT_USER: {{ .Values.mysql.connection.user | b64enc | quote }}
  NEXT_PASSWORD: {{ .Values.mysql.connection.password | b64enc | quote }}
  REPLICA_PASSWORD: {{ .Values.mysql.connection.password | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.connection.rootPassword | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.connection.database | b64enc | quote }}
  TZ: {{ .Values.mysql.connection.timezone | b64enc | quote }}
{{- end }}