{{- if .Values.vault.connection.create }}
{{- if not .Values.vault.connection.caBundleSecretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vault-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.vault.connection.caBundle }}
---
{{- end }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq-cluster.labels" . | nindent 4 }}
spec:
  address: {{ .Values.vault.connection.server }}
  caCertSecretRef: {{ ternary .Values.vault.connection.caBundleSecretRef (printf "%s-vault-ca" .Release.Name) .Values.vault.connection.caBundleSecretRef }}
---
{{- end }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq-cluster.labels" . | nindent 4 }}
spec:
  vaultConnectionRef: {{ ternary .Release.Name .Values.vault.connectionRef .Values.vault.connection.create }}
  method: kubernetes
  mount: {{ .Values.vault.kubernetesAuthMountPath }}
  kubernetes:
    role: {{ .Values.vault.auth.role }}
    serviceAccount: {{ .Release.Name }}-server
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Release.Name }}-url
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq-cluster.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Release.Name }}
  mount: {{ .Values.vault.kvEngine.mountPath }}
  type: kv-{{ .Values.vault.kvEngine.version }}
  path: {{ .Values.initdb.owner.vaultSecretPath }}
  refreshAfter: 10m
  rolloutRestartTargets:
    - name: {{ .Release.Name }}-server
      kind: StatefulSet
  destination:
    name: {{ .Release.Name }}-url
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        host:
          text: |
            {{ `{{- printf "amqp://%s:%s@` }}{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ ternary "5671" "5672" .Values.tlsEnabled }}{{ `" (get .Secrets "username") (get .Secrets "password") -}}` }}