apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hsr.name" . }}-next
  labels:
    app.kubernetes.io/name: {{ include "hsr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  DATABASE_URL: {{ include "hsr.dbConnectionString" . | b64enc | quote }}
  REDIS_URL: {{ include "hsr.redisConnectionString" . | b64enc | quote }}
  NEXTAUTH_URL: {{ .Values.next.nextAuth.url | b64enc | quote }}
  NEXTAUTH_SECRET: {{ .Values.next.nextAuth.secret | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.next.nextAuth.googleClientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.next.nextAuth.googleClientSecret | b64enc | quote }}