apiVersion: v1
kind: Service
metadata:
  name: {{ include "hsr.name" . }}-next
spec:
  selector:
    app: {{ include "hsr.name" . }}-next
  ports:
    - protocol: TCP
      port: {{ int (default 3000 .Values.next.port) }}
      targetPort: 3000
